version: '3.8'

services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
                VERSION: ${PHP_VERSION:-8.2}
        expose:
            - 9000
        restart: unless-stopped
        environment:
            ROLE: app
            APPENV: ${APP_ENV:-production}
        volumes:
            - ./docker/php.ini:/etc/php/${PHP_VERSION}/cli/conf.d/php.ini
            - .:/var/www/html
        networks:
            - net
        depends_on:
            - mysql

    webserver:
        image: nginx:1.24.0-alpine
        ports:
            - 8002:80
        restart: unless-stopped
        environment:
            - NGINX_HOST=localhost
            - NGINX_PORT=80
        volumes:
            - ./docker/default.conf.template:/etc/nginx/templates/default.conf.template
            - ./:/var/www/html
        networks:
            - net
        depends_on:
            - app
            - mysql

    mysql:
        image: mariadb:10.11.2-jammy
        ports:
            - 3302:3306
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: "${DB_DATABASE:-secret}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-secret}"
            MYSQL_PASSWORD: "${DB_PASSWORD:-secret}"
            MYSQL_USER: "${DB_USERNAME:-secret}"
        volumes:
            - db:/var/lib/mysql
        networks:
            - net
        healthcheck:
            test:
              [
                  "CMD",
                  "mysqladmin",
                  "ping",
                  "-h",
                  "localhost",
                  "-u${DB_USERNAME}",
                  "-p${DB_PASSWORD}"
              ]
            retries: 3
            timeout: 5s

networks:
    net:
        driver: bridge

volumes:
    db:
        driver: local
